### PR TITLE
added dropdown to products nav menu that links to views by product type

### PR DESCRIPTION
**Pull request by THATBLADEBOY**
# Description

**Given** the user is on any page of the Bangazon site
**When** the user performs a gesture on a product category name
**Then** a list of all products in that category will be displayed, with title, quantity, and price/unit

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

```
git fetch -a
git checkout ab-ticket4
```
1. Confirm that "Products" nav item goes to the index list of all products when the word "Products" is clicked.
2. Confirm that each item in the dropdown next to Products nav item goes to the view of the specific product category and lists the products' titles, quantities, and prices.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jdbbaugh — APPROVED** [review]
Works as stated 🍺

**Review by colebryant — APPROVED** [review]
Sweetness

**Review by dakotacookson — APPROVED** [review]
Works great

**Review by askingalot — CHANGES_REQUESTED** [review]
There should not be specific methods for each category. This application is data-driven. If we add a new category, the user should be able to see that category and products in it.

**Comment by THATBLADEBOY** [comment]
Removed the dropdown menu and made each instance of a product type a link to that product type's view.

### Testing Instructions

```
git pull origin ab-ticket4
```
Click the "Products" nav item and confirm that each product's product type is a link that directs to the product type view. (a list of all products with that product type"

**Pull request closed without merging**
